config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  	root 'pictures#new'
	resources :pictures do 
		resources :comments
		resources :replies
	end
	resources :comments do
		resources :replies
	end
	resources :categories
	resources :blogs
	get '/images' => 'pictures#images'
	get '/logo' => 'pictures#logo'
	get '/about' => 'pictures#about'
	get '/category' => 'pictures#category'
	get '/home' => 'pictures#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	mount_uploader :image, AvatarUploader
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
	has_many :comments
	has_many :replies
	validates :title, presence: true,
             length: { minimum: 5 }
  validates :text, presence: true,
             length: { minimum: 5 }
  mount_uploader :photo, AvatarUploader

end

app/models/reply.rb
class Reply < ApplicationRecord
	belongs_to :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	def new
		@blog = Blog.new
	end

	def index
		if params[:title].present?
      @blog = Blog.where("title like ?", "%#{params[:title]}%")
    else
     @blog = Blog.all
    end
	end

	def create

		@blog = Blog.new(title: params[:blog][:title], image: params[:blog][:image])
		@blog.save
		redirect_to @blog
	end

	def show
		@blog = Blog.find(params[:id])
	end

	def edit
		@blog = Blog.find(params[:id])
	end

	def destroy
		@blog = Blog.find(params[:id])
		@blog.destroy
		redirect_to blogs_path
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@category = Category.all
	end

	def create
		@category = Category.new(title: params[:category][:title], description: params[:category][:description])
		@category.save
		redirect_to @category
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
	
	@picture = Picture.find(params[:picture_id])	
	@comment = @picture.comments.create(comments: params[:comment][:comments], body: params[:comment][:body])
	@comment.save
	redirect_to picture_path(@picture)
	end



	
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	def new
		@picture = Picture.new
	end
	def create
		@picture = Picture.new(title: params[:picture][:title], text: params[:picture][:text], photo: params[:picture][:photo])
		if @picture.save
		redirect_to @picture
	  else
		render 'new'
	 end
	end

	def index
		@pictures = Picture.all
	end

	def show
		
		@picture = Picture.find(params[:id])
	end

	def edit
		@picture = Picture.find(params[:id])
	end

	def update
		@picture = Picture.find(params[:id])
		if @picture.update(title: params[:picture][:title], text: params[:picture][:text])  
		redirect_to picture_path(@picture)
	else
		render'edit'
	 end
	end

	def destroy
 		@picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_path
	end

	def images
    @pictures = Picture.all
	end

	def logo
	end

	def about
	end

	def home
	end

	def category
	end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
	def create
		@picture = Picture.find(params[:picture_id])
		@reply = @picture.replies.create(reply: params[:reply][:reply])
		@reply.save
		redirect_to picture_path(@picture)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>
 
<%= form_for :blog, url: blogs_path(@blog) do |f| %>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 <p>
    <%= f.label :Image %><br>
    <%= f.file_field :image %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

 <%= form_for :blog, url: blogs_path, :method => 'get' do |f| %>
 <p>
 <%=text_field_tag :title %>
 <%= submit_tag "search" %>
 </p>
<% end %>

<table>
  <tr>
    <th>Title</th>
    <th>Image</th>
  </tr>
 
  <% @blog.each do |blog| %>
    <tr>
      <td><%= blog.title %></td>
      <td> <img src="<%= blog.image %>" style="height: 150px; width: 300px;"></td>
      <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
      <td><%= link_to 'Show', blog_path(blog) %></td>
      <td><%= link_to 'Destroy', blog_path(blog),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <p>
   <% end %>
</table>

app/views/blogs/new.html.erb
<%= form_for :blog, url: blogs_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 <p>
    <%= f.label :Image %><br>
    <%= f.file_field :image %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/blogs/show.html.erb
<h1> New Blog <h1>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>
 
<p>
  <strong>Image:</strong>

  <img src="<%= @blog.image %>" style="height: 150px; width: 300px;">
</p>
<%= link_to 'Back', blogs_path %>

app/views/categories/index.html.erb
<h1>Listing Articles</h1>

app/views/pictures/categories.html.erb
<div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Sellect Type
    <span class="caret"></span></button>
    <ul class="dropdown-menu">
      <li><a href="#">Animals</a></li>
      <li><a href="#">Nature</a></li>
      <li><a href="#">Mountains</a></li>
      <li><a href="#">Flowers</a></li>
      <li><a href="#">All</a></li>
    </ul>
  </div>
</div>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>
 
<%= form_for :picture, url: picture_path(@picture), method: :patch do |f| %>
 
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@picture.errors.count, "error") %> prohibited
        this picture from being saved:
      </h2>
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', pictures_path %>

app/views/pictures/images.html.erb
<div class="gallery">
  <a target="_blank" href="img_5terre.jpg">
    <img src="/assets/99.jpg" alt="" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_forest.jpg">
    <img src="/assets/3zj89jga8zr6aja5gwyrc1ain.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_lights.jpg">
    <img src="/assets/200.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/88.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/733538.jpg" alt="5Terre" class="image_size">
  </a>
</div>
 
 <div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/733542.jpg" alt="5Terre" class="image_size">
  </a>
</div>

 <div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/1212.png" alt="5Terre" class="image_size">
  </a>
</div>

 <div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/bicycle.jpg" alt="5Terre" class="image_size">
  </a>
</div>

 <div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/123.jpg" alt="5Terre" class="image_size">
  </a>
</div>

 <div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/1234.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/33.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/733536.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/88.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/77.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/555.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/999.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/777.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/7777.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/888.jpeg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/12.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/1212.png" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/1234.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/444.jpeg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/555.jpeg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/33.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/333.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/12.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/888.jpg" alt="5Terre" class="image_size">
  </a>
</div>

<div class="gallery">
  <a target="_blank" href="img_mountains.jpg">
    <img src="/assets/888.jpg" alt="5Terre" class="image_size">
  </a>
</div>


<style>
div.gallery {
    margin: 5px;
    border: 1px solid #ccc;
    float: left;
    height: 100px;
	width: 200px;
	margin-bottom: 35px;
}

div.gallery:hover {
    border: 1px solid #777;
}

div.gallery img {
    width: 100%;
    height: auto;
}

div.desc {
    padding: 15px;
    text-align: center;
}

</style>

app/views/pictures/index.html.erb
<h1>Listing Articles</h1>
 <%= link_to 'New picture', new_picture_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @pictures.each do |picture| %>
    <tr>
      <td><%= picture.title %></td>
      <td><%= picture.text %></td>
      <td><img src="<%= picture.photo %>" style="height: 120px; width: 150px;"></td>
      <td><%= link_to 'Show', picture_path(picture) %></td>
      <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
      <td><%= link_to 'Destroy', picture_path(picture),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

 

app/views/pictures/logo.html.erb
<div class="row">	
	<div class="gallery center">
	  <a target="_blank" href="logo.png">
	    <img src="/assets/logo.png " alt="5Terre" class="image_size">
	  </a>
	</div>
</div>

<style>
div.gallery {
    margin-left: 500px;
    border: 5px solid #ccc;
    height: 250px;
	width: 300px;
    text-align: center;
}

div.gallery:hover {
    border: 1px solid #777;
}

div.gallery img {
    width: 100%;
    height: auto;
}

div.desc {
    padding: 25px;
    text-align: center;
}
</style>

app/views/pictures/new.html.erb
<h1> New Picture <h1>
<%= form_for :picture, url: pictures_path  do |f| %>

<% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@picture.errors.count, "error") %> prohibited
        this picture from being saved:
      </h2>
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
<p>
    <%= f.label :Image %><br>
    <%= f.file_field :photo %>
  </p>
  
 
  <p>
    <%= f.submit %>
  </p>
<% end %>


<head>
<style>
body {
    background-image: url("/assets/200.jpg");
    background-repeat: no-repeat;
}
</style>
</head>

<style>
h1 {
    color: red;
}
</style>

app/views/pictures/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @picture.text %>
</p>
<p>
  <strong>Image:</strong>

  <img src="<%= @picture.photo %>" style="height: 150px; width: 300px;">
</p>

<h2>Comments</h2>
<% @picture.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.comments %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<!-- <h2>Replies</h2> -->

<% @picture.replies.each do |comment| %>
  <p>
    <strong>reply:</strong>
    <%= comment.reply %>
  </p>
   <% end %>

<h2>Add a comment:</h2>
<%= form_for([@picture, @picture.comments.build]) do |f| %>
  <p>
    <%= f.label :comments %><br>
    <%= f.text_field :comments %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<h2 class="">Add a reply:</h2>

<%= form_for([@picture, @picture.replies.build]) do |f| %>
  <p>
    <%= f.label :reply %><br>
    <%= f.text_field :reply %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', pictures_path %>